---
- hosts: brk0
  connection: local
  gather_facts: false 
  become: true
  roles:
  - role: ansible-role-asdf
    asdf_plugins:
    - name: "awscli"
      versions: ["2.13.30"]
      global: "2.13.30"
