---
- hosts: localhost
  connection: local
  gather_facts: false 
  become: true
  tasks:
  - name: install base packages
    community.general.pacman:
      name:
        # Main
        - ttf-jetbrains-mono # main font
        - noto-fonts         # unicode font
        - noto-fonts-emoji   # emojis
        # Shell
        - fish               # powerful shell
        - starship           # cross-shell prompt
        - git                #
        - exa                # powerful ls
        - bc                 # maths
        - jq                 # json processor
        - most               # colorized pager
        - bat                # colorized cat
        - tree               #
        - vi                 #
        - man                #
        - screen             # terminal multiplexer
        - asciinema          # term recorder
        - expect             # automation tool
        - arch-audit         # list vulnerabilities
        # System
        - htop               # system monitor
        - net-tools          # netstat
        - reflector          # mirror sorter
        - fwupd              # dell firmware updater
        - nmap               # port scanner
        - tcpdump            # packet analyzer
        - whois              # query registry
        - stress             # stress test tool
        # Disk
        - iotop              # disk "top"
        - ncdu               # disk usage analyzer
        # Network
        - nethogs            # net "top"
        - openssh            #
        - sshpass            # allow ansible -k
        - keychain           # ssh-agent wrapper
        - wget               # downloader
        - bind-tools         # dns tools
        # Utils
        - cronie             # Scheduler
        - at                 # Scheduler
        - borgbackup         # backup utility
        - borgmatic          # backup utility automation
        - pwgen              # random password generator
        - lsd                # improved ls command
        - rsync              # sync tool
        - rclone             # sync tool
        - syncthing          # sync tool
        - vdirsyncer         # sync tool
        - khal               # cli calendar manager
        - khard              # cli contacts manager
        - words              # dictionnaries
        - fzf                # fuzzy finder
        - neofetch           #
        - unzip              # uncompress zip
        - cifs-utils         #
        - shellcheck         # sh linter
        - oath-toolkit       # otp tool
        - dmidecode          # dump dmi table content
        - python-pre-commit  # pre-commit hook manager
        - zim                # wiki app
        - mailutils          # mail client
      state: present
  - name: Install asdf act
    ansible.builtin.shell: asdf install act 0.2.52 || true 
  - name: Set asdf global act
    ansible.builtin.shell: asdf global act 0.2.52 || true 
